<a href="https://colab.research.google.com/github/Ritesh-panda/NLP-Learnings/blob/main/Bagofwords.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv("/content/spam.csv")

In [3]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [7]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [8]:
df['spam']=df['Category'].apply(lambda x :1 if x=='spam' else 0)

In [9]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [13]:
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2, random_state=42)

In [18]:
v=CountVectorizer()
x_train_cv=v.fit_transform(x_train.values)
x_test_cv=v.transform(x_test.values)

In [19]:
x_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
x_train_np=x_train_cv.toarray()
x_test_np=x_test_cv.toarray()

In [22]:
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
x_test_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

###NAIVE BAYES CLASSIFIER

In [25]:
model=MultinomialNB()
model.fit(x_train_np,y_train)

MultinomialNB()

In [26]:
y_pred=model.predict(x_test_np)

In [28]:
classification_report=classification_report(y_test,y_pred)
print(classification_report)

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       966
           1       1.00      0.94      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

###testing wit a datapoint

In [30]:
msg='''Congratulations!!! You have WON ₹50,000 in our Lucky Draw!!! 💰💰

Click the link below immediately to claim your reward:
http://claim-prize-now-fast.com

Hurry! This offer expires in 10 minutes ⏳

Send your bank details, OTP, and Aadhaar number to verify your identity.

Reply YES to claim now!!'''
msg_cnt=v.transform([msg])
model.predict(msg_cnt)

array([1])